### ISSUE TITLE
Will the new dataset UAVVIC be released?

### ISSUE THREAD

**Issue by LeoHuang0511** [streamer-AP/CGNet#1]
Thanks for the exellent work! I'am wondering that if the UAVVIC dataset will be released publicly or not? Cause it's an interesting dataset which not only has the crowd scenes, but also has the vehicle data.

**Comment by streamer-AP** [comment]
Thanks for highlighting our work! Yes, it will be released soon as a benchmark. 
However, if it is helpful for your work,  I can also send it to you right now through email. 
My email address: liuxinyan19@mails.ucas.ac.cn
Looking forward to your contact
