### ISSUE TITLE
Model Mentioned in README is Expired and Unavailable

### ISSUE THREAD

**Issue by saran1995** [streamer-AP/CGNet#4]
Hello,

I would like to bring to your attention that the model referenced in the README file https://pan.baidu.com/s/1GZJM6sHlFULK56UTTlIhtg?pwd=pigo, https://drive.google.com/file/d/1EcEy11HVMDxPUMztC-zSIQ4jAMUStbDG/view?usp=drive_link has expired and is no longer available for download. Can you kindly update the model link, 

![image](https://github.com/user-attachments/assets/251ae27b-a87b-40b6-bd1f-6032619eb03a)

![image](https://github.com/user-attachments/assets/4badee86-cf9e-4b5f-85b8-9690e3a8d1d9)

Thankyou

**Comment by streamer-AP** [comment]
Thanks! You can try this one: 
link：https://pan.baidu.com/s/13WFuo-2kpb-SNxD42VVDQg 
pwd：n323

**Comment by streamer-AP** [comment]
But for the goolge link, it works for me. 
![1722341917308](https://github.com/user-attachments/assets/b30a9453-f9bb-492a-bfe7-fb43c64c01ec)

**Comment by streamer-AP** [comment]
And the readme.md is also updated
